version: "3.8"

volumes:
  delivery.db.data:
    driver: local

networks:
  delivery.network:
    driver: bridge

services:

  mongo:
    image: mongo
    restart: always
    container_name: delivery_mongo
    ports:
      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#      MONGO_INITDB_DATABASE: delivery_mongo_db
    networks:
      - delivery.network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
    networks:
      - delivery.network

  delivery.local:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: "delivery_service"
    env_file:
      - ./environment.env
    ports:
      - "4000:4000"
    working_dir: /app
    networks:
      - delivery.network
    depends_on:
      - delivery.db
      - mongo
    volumes:
      - ./:/app:delegated

  delivery.db:
    image: postgres:11.4
    container_name: "delivery_service_db"
    ports:
      - "5432:5432"
    networks:
      - delivery.network
    environment:
      - POSTGRES_DB=delivery_db
      - POSTGRES_PASSWORD=delivery
      - POSTGRES_USER=delivery
    volumes:
      - delivery.db.data:/var/lib/postgresql/data


